# Generated by Django 3.0.5 on 2024-03-04 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20240304_0753'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reunion',
            options={'verbose_name': 'Reunion', 'verbose_name_plural': 'Reuniones'},
        ),
    ]
